version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/new/aws-flask-app

permissions:

  - object: /home/ubuntu/new/aws-flask-app
    pattern: "*.sh"
    owner: ubuntu
    mode: 777
    type:
      - file

hooks:
  AfterInstall:
   - location: install_app_dependencies.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: start_server.sh
     timeout: 300
     runas: root
